kind: pipeline
name: default

steps:
  - name: building-clojure-app
    image: clojure:openjdk-11-lein
    commands:
    - lein uberjar

  - name: deploy-site
    pull: True
    image: appleboy/drone-scp
    settings:
      host: gasp.digitaloctave.com
      port: 22
      username:
        from_secret: ssh_user
      key:
        from_secret: ssh_key
      target: /var/www/belch-api/
      source:
        - /drone/src/*
        - target/uberjar/server.jar
        # - docker-compose.yml
        # - resources
        # - project.clj
        # - src
      strip_components: 2

  - name: launch
    pull: True
    image: appleboy/drone-ssh
    settings:
      host: gasp.digitaloctave.com
      port: 22
      username:
        from_secret: ssh_user
      key:
        from_secret: ssh_key
      port: 22
      command_timeout: 5m
      script:
        - cd /var/www/belch-api/
        - docker-compose down
        - docker-compose up -d 
#        - docker-compose exec jetty sh -c "lein migrate"
